# Generated by Django 4.1.3 on 2022-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendorprofile_merchantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customerAC',
            field=models.BooleanField(default=False, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='merchantAC',
            field=models.BooleanField(default=False, verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='user',
            name='vendorAC',
            field=models.BooleanField(default=False, verbose_name='Vendor'),
        ),
    ]
