# Generated by Django 4.1.3 on 2022-11-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_customerac_user_merchantac_user_vendorac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customerAC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='merchantAC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendorAC',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='owner',
        ),
    ]
