# Generated by Django 4.1.3 on 2022-11-29 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_customer_user_is_merchant_user_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('P', 'pending'), ('A', 'approved'), ('R', 'rejected')], default='P', max_length=1)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_descrption', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('P', 'pending'), ('A', 'approved'), ('R', 'rejected')], default='P', max_length=1)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MerchantProfile',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
