# Generated by Django 4.1.3 on 2022-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merchant_vendor_remove_vendorprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
