# Generated by Django 4.1.3 on 2022-11-29 13:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vendor_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbgbail9r/image/upload/v1669642977/tamu_foods_with_django/user_profile_image_n5g3kg.png', max_length=255, verbose_name='images/'),
        ),
    ]
