# Generated by Django 4.1.3 on 2022-12-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_is_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='merchant_descrption',
            new_name='merchant_description',
        ),
    ]
