# Generated by Django 4.1.3 on 2022-12-06 22:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_merchant_descrption_merchant_merchant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbgbail9r/image/upload/v1670364629/tamu_foods_with_django/profile_lvgqc5.png', max_length=255, verbose_name='images/'),
        ),
    ]
