# Generated by Django 4.1.3 on 2022-11-11 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='foodproductcategory',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='product',
        ),
        migrations.AlterField(
            model_name='foodorderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='food_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='tamueats.discounts'),
        ),
    ]
