# Generated by Django 4.1.3 on 2022-11-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
