# Generated by Django 4.1.3 on 2022-12-02 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0007_alter_foodproductcategory_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='food_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbgbail9r/image/upload/v1669985026/tamu_foods_with_django/food_avkxmo.png', max_length=255, verbose_name='images/'),
        ),
    ]
