# Generated by Django 4.1.3 on 2022-12-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0008_foodproduct_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
