# Generated by Django 4.1.3 on 2022-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0009_alter_foodorderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
