# Generated by Django 4.1.3 on 2022-12-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0010_alter_foodorderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorderitem',
            name='unit_price',
        ),
    ]
