# Generated by Django 4.1.3 on 2022-12-05 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0011_remove_foodorderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
