# Generated by Django 4.1.3 on 2022-12-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0012_alter_foodorderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPerson', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
