# Generated by Django 4.1.3 on 2022-12-06 22:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamueats', '0013_deliverorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='food_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dbgbail9r/image/upload/v1670364631/tamu_foods_with_django/food_qosmsg.png', max_length=255, verbose_name='images/'),
        ),
    ]
